/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on May 23, 2010, 8:17:22 PM
 */

package org.chocolate_milk.example;

import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import org.chocolate_milk.Constants;
import org.chocolate_milk.controller.Client;
import org.chocolate_milk.controller.NetClient;
import org.chocolate_milk.controller.NetServer;
import org.chocolate_milk.controller.Utils;
import org.chocolate_milk.controller.jacob.FileModeE.FILE_MODE;
import org.chocolate_milk.model.AccountQueryRq;
import org.chocolate_milk.model.AccountRet;
import org.chocolate_milk.model.QBXML;
import org.chocolate_milk.model.QBXMLMsgsRq;
import org.chocolate_milk.model.QBXMLMsgsRqItem;
import org.chocolate_milk.model.QBXMLMsgsRsItem;
import org.chocolate_milk.model.types.QBXMLMsgsRqItemOnErrorType;

/**
 *
 * @author ryan
 */
public class JFrameConnect extends javax.swing.JFrame {



    
    
    /** Creates new form NewJFrame */
    public JFrameConnect() {
        initComponents();
        for(FILE_MODE mode : FILE_MODE.values()){
            jComboBox1.addItem(mode);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new JTextArea(){
            private void updateTextArea(final String text) {
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        jTextArea1.append(text);
                    }
                });
            }

            private void redirectSystemStreams() {
                OutputStream out = new OutputStream() {
                    @Override
                    public void write(int b) throws IOException {
                        updateTextArea(String.valueOf((char) b));
                    }

                    @Override
                    public void write(byte[] b, int off, int len) throws IOException {
                        updateTextArea(new String(b, off, len));
                    }

                    @Override
                    public void write(byte[] b) throws IOException {
                        write(b, 0, b.length);
                    }
                };

                System.setOut(new PrintStream(out, true));
                System.setErr(new PrintStream(out, true));
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chocolate Milk");

        jButton1.setText("Start NetServer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("chocmilk");

        jTextField2.setText("chocmilk");

        jTextField3.setText("Y:\\\\MyQbFile.qbw");

        jTextField4.setText(Constants.CONSTANTS.SERVER_PORT.getProperty());
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel1.setText("QB File Name");

        jLabel2.setText("File Mode");

        jLabel3.setText("AppId");

        jLabel4.setText("AppName");

        jLabel5.setText("Port Number");

        jButton2.setText("Test Server");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField3)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(253, 253, 253)))
                        .addGap(46, 46, 46))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private NetServer instance=null;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        if(instance == null || instance.isShutdown()){

            String fileName=jTextField3.getText();
            int fileMode=((FILE_MODE)jComboBox1.getSelectedItem()).getValue();
            String appId = jTextField2.getText();
            String appName=jTextField1.getText();
            int port = Integer.parseInt(jTextField4.getText());
            instance = new NetServer(fileName, fileMode, appId, appName,port);
            Thread thread = new Thread(instance);
            thread.start();
            jButton1.setText("Shutdown NetServer");
        
        } else {

            
            instance.setShutdown(true);
            jButton1.setText("Start NetServer");


        }

    } catch(Exception e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        NetClient sender = new NetClient(Constants.CONSTANTS.SERVER_ADDRESS.getProperty(), Integer.parseInt(jTextField4.getText()));

         Test test1 = new Test(sender, jTextArea1);
        Test test2 = new Test(sender, jTextArea1);
        Test test3 = new Test(sender, jTextArea1);

       Thread thread1 = new Thread(test1);
        Thread thread2 = new Thread(test2);
        Thread thread3 = new Thread(test3);

        try {
            jTextArea1.append("Starting Threads...\n");

            thread1.start();
            thread2.start();
            thread3.start();
         
            jTextArea1.append("Done...Bye!\n");
        } catch (Exception e){
            e.printStackTrace();
        }



    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameConnect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
class Test implements Runnable {
    private Client client;
    private JTextArea area1;
    public Test(Client client, JTextArea area1){
        this.client=client;
        this.area1=area1;
    }

     public void doExchange() throws Exception {

        QBXML qbxml = Utils.getRequestDocument(QBXMLMsgsRqItemOnErrorType.STOPONERROR);

        QBXMLMsgsRq request = qbxml.getQBXMLSequence().getQBXMLSequenceChoice().getQBXMLMsgsRq();

        QBXMLMsgsRqItem qBXMLMsgsRqItem = new QBXMLMsgsRqItem();

        AccountQueryRq accountQueryRq = new AccountQueryRq();

        qBXMLMsgsRqItem.setAccountQueryRq(accountQueryRq);

        request.addQBXMLMsgsRqItem(qBXMLMsgsRqItem);

        QBXML response = client.exchangeXML(qbxml);

        QBXMLMsgsRsItem item = response.getQBXMLSequence2().getQBXMLSequence2Choice().getQBXMLMsgsRs().getQBXMLMsgsRsItem(0);
        AccountRet[] rets = item.getAccountQueryRs().getAccountRet();


        area1.append("Accounts: \n");

        for (AccountRet ret : rets) {
            area1.append(ret.getFullName() + "\n");


        }
        area1.append("Account List Size ----> " + rets.length + "\n" );


    }


     public void run() {


        try {



            for (int i = 0; i < 7; i++) {
                area1.append("About to launch test #" + i + " with thread " + Thread.currentThread().getName() + "\n" );
                doExchange();
                area1.append("Test cycle #" + i + " launched with thread " + Thread.currentThread().getName() + "\n");
            }

            area1.append("Thread " + Thread.currentThread().getName() + " finished the test cycles.");



        } catch (Exception e) {
            e.printStackTrace();
            System.err.println(e.getMessage());
        }


    }


}